// SPDX-License-Identifier: MIT
// Copyright (c) 2025. Csaba Dudas (CsabaDu)

namespace CsabaDu.DynamicTestData.Core.TestDataTypes.Interfaces;

/// <summary>
/// Represents a base interface for test data that has a primary test parameter for test case result.
/// </summary>
public interface IExpected
{
    /// <summary>
    /// Gets the prefix applied to the result strings generated by the operation.
    /// </summary>
    string ResultPrefix { get; }

    /// <summary>
    /// Returns the expected value of the test case.
    /// </summary>
    object GetExpected();
}

/// <summary>
/// Marker interface for test cases validating method return values.
/// Inherits from <see cref="IExpected"/> and marks test data designed to return a value.
/// </summary>
/// <remarks>
/// Serves as a semantic indicator for tests verifying successful execution paths with return values.
/// </remarks>
public interface IReturns
: IExpected;

/// <summary>
/// Marker interface for test cases validating exception throwing behavior.
/// Inherits from <see cref="IExpected"/> and marks test data designed to throw an exception.
/// </summary>
/// <remarks>
/// Identifies tests verifying error handling and exceptional execution paths.
/// </remarks>
public interface IThrows
: IExpected;