// SPDX-License-Identifier: MIT
// Copyright (c) 2025. Csaba Dudas (CsabaDu)

namespace CsabaDu.DynamicTestData.Core.TestDataTypes.Interfaces;

/// <summary>
/// Represents a base interface for test data that has a primary test parameter for test case result.
/// </summary>
public interface IExpected
{
    /// <summary>
    /// Gets the prefix applied to the result strings generated by the operation.
    /// </summary>
    string ResultPrefix { get; }

    object GetExpected();
}

public interface IExpected<out TResult>
: IExpected
where TResult : notnull
{
    /// <summary>
    /// Gets the strongly typed expected result of the test case.
    /// </summary>
    TResult Expected { get; }
}

/// <summary>
/// Marker interface for test cases validating method return values.
/// Inherits from <see cref="IExpected"/> and marks test data designed to return a value.
/// </summary>
/// <remarks>
/// Serves as a semantic indicator for tests verifying successful execution paths with return values.
/// </remarks>
public interface IReturns
: IExpected;

public interface IReturns<out TResult>
: IExpected<TResult>,
IReturns
where TResult : notnull;

/// <summary>
/// Marker interface for test cases validating exception throwing behavior.
/// Inherits from <see cref="IExpected"/> and marks test data designed to throw an exception.
/// </summary>
/// <remarks>
/// Identifies tests verifying error handling and exceptional execution paths.
/// </remarks>
public interface IThrows
: IExpected;

public interface IThrows<out TException>
: IExpected<TException>,
IThrows
where TException : Exception;